version: '3.8'

services:
  hiit-timer:
    build: .
    ports:
      - "9012:9012"
    volumes:
      #- ./data:/app/data
      - hiit_etc:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      
volumes:
  hiit_etc: